spring:
  application:
    name: deployment-webhook-test
  jackson:
    default-property-inclusion: non_null

server:
  port: 8080
  servlet:
    context-path: /

management:
  endpoints:
    web:
      exposure:
        include: health,info,env,logs,metrics
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    root: INFO
    com.test.dynatrace: DEBUG
